### ISSUE TITLE
TypeError on run

### ISSUE THREAD

**Issue by lucasjohnston** [paazmaya/yaml-validator#20]
### Expected behaviour

Should have validated yaml file.

### Actual behaviour

```
/usr/local/lib/node_modules/yaml-validator/index.js:129
    const lineNumber = error.message.match(/line (\d+)/)[1];
                                                        ^

TypeError: Cannot read property '1' of null
    at YamlValidatore.loadData (/usr/local/lib/node_modules/yaml-validator/index.js:129:57)
    at YamlValidatore.loadFile (/usr/local/lib/node_modules/yaml-validator/index.js:158:15)
    at YamlValidatore.checkFile (/usr/local/lib/node_modules/yaml-validator/index.js:167:20)
    at mapFiles (/usr/local/lib/node_modules/yaml-validator/index.js:201:18)
    at Array.map (<anonymous>)
    at YamlValidatore.validate (/usr/local/lib/node_modules/yaml-validator/index.js:200:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yaml-validator/bin/yaml-validator.js:112:11)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
```

### Versions and environment

 * Operating system: Mac OS X
 * Node.js: v11.2.0
 * npm: 6.4.1
 * yaml-validator: 1.3.0

**Comment by paazmaya** [comment]
How does the command for getting this looks like and against what kind of a file?
